DROP DATABASE IF EXISTS polarium;
CREATE DATABASE polarium;
USE polarium;
CREATE TABLE users (
    user_id BIGINT NOT NULL PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    phone TEXT,
    aff BIGINT,
	aff_model TEXT,
    afftrack TEXT,
    platform TEXT,
    first_name TEXT,
    last_name TEXT,
    registered DATETIME,
    country TEXT,
    currency TEXT,
    balance DOUBLE,
    training_currency TEXT,
    training_balance DOUBLE,
    age TEXT,
    gender TEXT,
    city TEXT,
    pnl DOUBLE,
    deposits BIGINT,
    withdrawals BIGINT,
    deposits_count BIGINT
);
CREATE TABLE deposits (
    transaction_id BIGINT NOT NULL PRIMARY KEY,
    transaction_amount DOUBLE,
    user_id BIGINT NOT NULL,
    country_name TEXT,
    transaction_type TEXT,
    transaction_created DATETIME,
    transaction_updated DATETIME,
    paygate TEXT,
    payment_method TEXT,
    paysystem TEXT,
    transaction_platform_name TEXT,
    transaction_platform_group TEXT,
    aff_id BIGINT,
    aff_model TEXT,
    traffic_group TEXT,
    registration_date DATETIME,
    registration_platform_name TEXT,
    registration_platform_group TEXT
);
CREATE TABLE trades (
    user_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL PRIMARY KEY,
    position_created DATETIME,
    position_closed DATETIME,
    instrument_type TEXT,
    asset TEXT,
    instrument_direction TEXT,
    total_investment DOUBLE,
    investment_real DOUBLE,
    investment_bonus DOUBLE,
    total_volume DOUBLE,
    volume_real DOUBLE,
    volume_bonus DOUBLE,
    gross_pnl DOUBLE,
    net_pnl_real DOUBLE,
    pnl_bonus DOUBLE,
    total_result DOUBLE,
    result_real DOUBLE,
    result_bonus DOUBLE,
    leverage DOUBLE,
    state TEXT,
    close_reason TEXT
);